kind: ReplicaSet
apiVersion: apps/v1
metadata:
    name: myrs
spec:
  replicas: 4
  selector:
     matchLabels:
       app: web
  template:
    metadata:
      name: mypod
      labels:
        app: web
    spec:
      containers:
        - name: mycont
          image: lerndevops/samplepyapp:v1
          ports:
           - containerPort: 3000

---

kind: Service 
apiVersion: v1
metadata: 
  name: mysvc
spec:
  type: NodePort
  ports: 
    - port: 3000
      nodePort: 30005
  selector:
     app: web
